### ISSUE TITLE
Distance and Direction - Circle - transparent fill not rendering in Firefox.  Text is black.

### ISSUE THREAD

**Issue by pshowalter** [ArcGIS/military-tools-webappbuilder#100]
@MarkTorrey 
On internal test server "ma2".
Circle - Interactive with Map Point tool, or keyed in coordinates.
Fill does not appear in Firefox, and "Radius" label text is black.  IE and Chrome have blue text and transparent fill working.

**Comment by MarkTorrey** [comment]
@pshowalter, What version of FF are you using? This is the output from 48.0 here on my machine
![screenshot from 2016-08-11 13-33-07](https://cloud.githubusercontent.com/assets/1084420/17598406/53d5b926-5fc8-11e6-9a04-36a58b1c0853.png)

**Comment by pshowalter** [comment]
47.0.1
![image](https://cloud.githubusercontent.com/assets/6842145/17598758/02918fde-5fca-11e6-8978-9df971c566ef.png)

**Comment by nfeuerstein** [comment]
Verified that at v48 the output is as expected.  Closing.
