### ISSUE TITLE
Range ring dialog units not matching label results

### ISSUE THREAD

**Issue by mfunk** [ArcGIS/military-tools-webappbuilder#105]
In testing range ring labels in the widget, I'm seeing a difference between the unit selected in the dialog (kilometers) and the units of the resulting labels (meters). For example, as I type **200** for the interval and select **kilometers** for the units I'm expecting to see labels for 200, 400, 600, 800, 1000 for the 5 rings. However I'm actually getting 200000, 400000, 600000, 800000, 1000000.

![image](https://cloud.githubusercontent.com/assets/3093182/17668041/6c65c78c-62bc-11e6-8a7e-148232eb6d77.png)

I'm not sure if this is as-designed, that output will always be meters, or not. Can anyone verify?

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#730
