### ISSUE TITLE
Ellipse rotation not drawn in IE and Firefox

### ISSUE THREAD

**Issue by mfunk** [ArcGIS/military-tools-webappbuilder#106]
I'm testing the Ellipse (semi, interactive draw on map) where I'm selecting a center point, then drawing the major axis end point about 65-ish degrees from north away, then drawing the minor axis. This works fine in Chrome...
![image](https://cloud.githubusercontent.com/assets/3093182/17706356/90d964aa-6390-11e6-9edd-a5f1134b6462.png)

But this isn't the case in Internet Explorer, where the final, ellipse drawn is drawn almost perpendicular to latitude line:
![image](https://cloud.githubusercontent.com/assets/3093182/17706476/0ca0c2a4-6391-11e6-91db-d859627dcc11.png)

... Firefox has the same problem:
![image](https://cloud.githubusercontent.com/assets/3093182/17706479/0fd46e1c-6391-11e6-8ec5-74f95685decb.png)

**Comment by adgiles** [comment]
@mfunk @nfeuerstein 

I cannot replicate this issue:
IE: 11.0.9600.16384
FF: 50.0.2

![ie](https://cloud.githubusercontent.com/assets/3740334/21102187/f7388672-c074-11e6-95e0-106c32f5e930.png)
![ff](https://cloud.githubusercontent.com/assets/3740334/21102190/fa6662c4-c074-11e6-9509-8fb246d8e15b.png)

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#729
