### ISSUE TITLE
Ellipse not drawing when keying in coordinate and other parameters Major, Minor, Unit, Orientation

### ISSUE THREAD

**Issue by pshowalter** [ArcGIS/military-tools-webappbuilder#107]
I have keyed in parameters as in screen caputure, but not getting ellipse.

![image](https://cloud.githubusercontent.com/assets/6842145/18019295/539a35b2-6ba9-11e6-97cb-514f5e96dad0.png)

**Comment by elinz** [comment]
@kgonzago @ACueva The fix for this issue was committed to the https://github.com/Esri/solutions-webappbuilder-widgets repo, however, Jenkins is building from this repo.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#728
