### ISSUE TITLE
Coordinate Conversion "Unable to determine input coordinate type"

### ISSUE THREAD

**Issue by mfunk** [ArcGIS/military-tools-webappbuilder#108]
Type (not paste) in the following coordinates for Mexico City: _19.4326 N, 99.1332 W_ and we get the error: "Unable to determine input coordinate type".

![image](https://cloud.githubusercontent.com/assets/3093182/19049661/3885c5c8-8960-11e6-8c3e-5e3f59d031c8.png)

The coordinates are valid in Google Maps:
![image](https://cloud.githubusercontent.com/assets/3093182/19049719/6c6b1dd4-8960-11e6-85aa-325371690a36.png)

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#727
