### ISSUE TITLE
No input parameter for visibility GP service in Visibility Widget settings page

### ISSUE THREAD

**Issue by kgonzago** [ArcGIS/military-tools-webappbuilder#112]
There isn't an input parameter for the user to supply the visibility GP service in the Visibility widget settings page. The "OK" button does not work for LLOS and RLOS widget.

The visibility widget that @adgiles created is not part of the release for Military Tools and that widget should be part of the release.

**Comment by nfeuerstein** [comment]
@kgonzago it was my understanding the visibility widget that was created under the Military Workflows team was a no-go, so the plan has been to use the widget that @adgiles created as the Visibility widget for Military Tools for ArcGIS.  Is that your understanding as well and is this issue still relevant?

**Comment by kgonzago** [comment]
@nfeuerstein Yes. It was agreed we should use AirC2's visibility for MTA. I will close out this issue.
