### ISSUE TITLE
Distance and Direction tool crashes browser with WGS84 basemap

### ISSUE THREAD

**Issue by dromy** [ArcGIS/military-tools-webappbuilder#116]
Measuring a distance and direction causes the browser to crash when the basemap is using WGS84 (4326).
To reproduce create an app with a map that uses a basemap in WGS84, Launch the Distance and Direction tool, Select a start point at Perth, Australia with endpoint at Istanbul  Turkey. 
Chrome 58 , browser becomes unresponsive
Edge 38, browser becomes unresponsive
Firefox 45, see attached images.
 
![distancetoolbug](https://user-images.githubusercontent.com/13754550/27331217-ee9b1b6c-55ff-11e7-9a0c-72c6b454111f.PNG)
![distancetoolbug2](https://user-images.githubusercontent.com/13754550/27331257-144d995c-5600-11e7-9321-f847ff1619a1.PNG)

**Comment by kgonzago** [comment]
@mdrom This issue was fixed in this [PR](https://github.com/Esri/solutions-webappbuilder-widgets/pull/910). It will be part of the Military Tools release June 27th.

**Comment by kgonzago** [comment]
@mdrom If you have anymore issues to report regarding military widgets (coordinate conversion, visibility, and distance and direction), those widgets can be found [here](https://github.com/Esri/solutions-webappbuilder-widgets)
