### ISSUE TITLE
Unable to add the Distance and Direction widget to portal for ArcGIS WebApplication Builder

### ISSUE THREAD

**Issue by topowright-zz** [ArcGIS/military-tools-webappbuilder#55]
I am able to add and configure the widget; however, the widget does not load: 

![image](https://cloud.githubusercontent.com/assets/5488313/15557883/b1e65014-228a-11e6-935c-0482f2435207.png)

**Comment by kgonzago** [comment]
@topowright which portal instance did you try adding this widget to? NSEC?

**Comment by topowright-zz** [comment]
@kgonzago was able to find the issue. When using a widget in a hosted portal you must make sure that all files are named properly. The settings files and feeback.json was lower case and needed to be uppercase. This is not an issue when using the developer edition, but is on a hosted instance of portal.
