### ISSUE TITLE
Visibility Widget Fails to load in WAB 2.1

### ISSUE THREAD

**Issue by ACueva** [ArcGIS/military-tools-webappbuilder#63]
Added Widget to:
WebAppBuilderForArcGIS\client\stemapp\widgets\Visibility folder

added

Visibility to list.json

Widget fails to load.
![5-27-2016 3-44-44 pm](https://cloud.githubusercontent.com/assets/3093940/15622911/c6d262e4-2422-11e6-851b-8c3b9b3c5a66.png)

**Comment by kgonzago** [comment]
@ACueva Simple fix. I'll reassign to myself.

**Comment by ACueva** [comment]
thanks @kgonzago

**Comment by kgonzago** [comment]
@ACueva I tested with the latest visibility widget and it didn't thrown that exception you experienced. This issue was submitted May 27 and changes were added to fix that issue on June 2. Can you test using the latest widget when you get a chance?

**Comment by ACueva** [comment]
@kgonzago, tested, it no longer throws an error and appears to load fine.

**Comment by kgonzago** [comment]
@ACueva Excellent. I'll close out this issue.
