### ISSUE TITLE
Coordinate Location icon should be a configurable symbol

### ISSUE THREAD

**Issue by MarkTorrey** [ArcGIS/military-tools-webappbuilder#81]
The icon used to display the current coordinate on the map is hard to small and hard to visualize against different basemaps (i.e. imagery). This needs to be updated to use standard map symbology symbol that can be adjusted by the user in the widget settings. @mcalamito  @topowright

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#734
