### ISSUE TITLE
Range Rings Center Point Issues

### ISSUE THREAD

**Issue by topowright-zz** [ArcGIS/military-tools-webappbuilder#87]
Range Rings center point does not stay the same. When selecting the center point your graphics draw, but when you select the last ring the center point moves. Seems to be a projection issue. Here is an example: 
**During the edit:** 
![image](https://cloud.githubusercontent.com/assets/5488313/17000775/09de0950-4e79-11e6-9a47-67c87d9187e4.png)
**After submitting the graphics:** 
![image](https://cloud.githubusercontent.com/assets/5488313/17000807/26a4481a-4e79-11e6-9a2d-607922baa8df.png)

**Comment by topowright-zz** [comment]
This seems to now fix the issue with the graphics jumping; however, there is still an issue with how the graphics are being projected possibly. This is the an example of my results from testing:  

![image](https://cloud.githubusercontent.com/assets/5488313/17037476/f2725cee-4f45-11e6-97b2-9a135a865df1.png)

**Comment by topowright-zz** [comment]
@kgonzago

**Comment by kgonzago** [comment]
@topowright Please confirm fix.

**Comment by topowright-zz** [comment]
verified
