### ISSUE TITLE
Distance and Direction widget - Circle - typed Center Point and Radius, circle disappears 

### ISSUE THREAD

**Issue by pshowalter** [ArcGIS/military-tools-webappbuilder#94]
@MarkTorrey 
Using Distance and Direction Widget - Circle - typed Center Point and Radius, circle disappears after entering the Center Point, and Radius, and hitting Enter.  The feedback circle is present until user hits enter, then circle disappears.

**Comment by MarkTorrey** [comment]
Thanks @pshowalter , Taking a look at this now

**Comment by pshowalter** [comment]
Working in my local WAB.  12:12 pm download on 8/11.
Working on internal test server "ma2".
