### ISSUE TITLE
Distance and Direction widget - Circle - Distance Calculator not working

### ISSUE THREAD

**Issue by pshowalter** [ArcGIS/military-tools-webappbuilder#95]
@MarkTorrey 
On Circle Tab, with Rate expanded, Click center point and enter 33.614073N 117.910292W, Enter 42 minutes, 45 miles/hour, should get circle in Newport Beach, CA area.  No circle is displayed.
![image](https://cloud.githubusercontent.com/assets/6842145/17342248/48f124c2-58c6-11e6-8a66-f5e6d87a0019.png)

**Comment by MarkTorrey** [comment]
@pshowalter, can you re-verify this after @kgonzago has merged the PR

**Comment by pshowalter** [comment]
Looks good.  Perhaps not zoomed out far enough when first tested?

![image](https://cloud.githubusercontent.com/assets/6842145/17600489/b3ebd76a-5fd1-11e6-9025-c713fe01b7da.png)

**Comment by MarkTorrey** [comment]
Cool, thanks @pshowalter
