### ISSUE TITLE
Coordinate Conversion widget produces different MGRS, USNG output than ArcMap and Pro Addin

### ISSUE THREAD

**Issue by pshowalter** [ArcGIS/military-tools-webappbuilder#97]
@MarkTorrey @topowright 
In the Coordinate Conversion Widget, enter **44.676 -121.028** in the Input box.  MGRS output will be **10TFQ5629748850**.

Use same Input coordinate in  ArcMap or Pro Coordinate Conversion Addin, MGRS output is **10TFQ5629848851**

Widget results in  USNG **10T FQ 56297 48850**, ArcMap Addin results in **10TFQ5629848851**

Widget results in DMS **44° 40' 33.60"N 121° 01' 40.80"W**, ArcMap Addin results in **44° 40' 33.6"N 121° 1' 40.8"W** (issue in Minutes portion containing leading and trailing zero's, coordinates are equivalent).

**Comment by pshowalter** [comment]
@MarkTorrey - Still seeing different MGRS Output in the Addin when compared to Widget.  The differnce is about 70 inches on the ground.  This is based on test downloaded this morning of _current, and the test site "ma2".

**Comment by MarkTorrey** [comment]
@pshowalter, Let me update ma2, don't think it's current after that last pr

**Comment by MarkTorrey** [comment]
@pshowalter, ok it's up to date now
